### ISSUE TITLE
the unsubscribe function

### ISSUE THREAD

**Issue by TomZhong-au** [Timonwa/react-chat#4]
hello, in lane 34 in the CheckBox.js file, should we call the unsubscribe function as follows?

    return () => unsubscribe()

**Comment by Timonwa** [comment]
hi @TomZhong-au , i am sorry, I am just seeing your issue. 

Thank you for your question. You should return the' unsubscribe' function in the `CheckBox.js` file on line 34 without invoking it immediately. Like so:

```
return () => unsubscribe;
```

This way, you're returning a reference to the unsubscribe function, allowing the caller to choose when to unsubscribe from the listener.

If you have any more questions or need further clarification, please feel free to ask.
